version: '2'
# docker-compose file
# 4 containers
#   2 of them to talk to each other - segregated by net - site1.com
#   2 of them to talk to each other - segregated by net - site2.com
# all four share a common volume
# 
# to be running an endpoint to send a message via http,
# and write the payload to the shared volume.
# 
# Use any language I want.
# no authentication

#bonus: with a load balancer in front
#  nginx, http_proxy, 
# 

services:
    load-balancer:
      build: load-balancer
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /tmp/shared_logs:/tmp/shared_logs
        - /var/run/docker.sock:/tmp/docker.sock:ro
      links:
        - flask-site-a
        - flask-site-b
        - node-site-a
        - node-site-b
      ports:
        - 80:80
      networks:
        - node-network
        - flask-network
    flask-site-a:
       build: ./flask-site
       volumes:
         - /tmp/shared_logs:/tmp/shared_logs
       ports:
         - 8081:8080
       networks:
         - flask-network
    flask-site-b:
       build: ./flask-site
       volumes:
         - /tmp/shared_logs:/tmp/shared_logs
       ports:
         - 8082:8080
       networks:
         - flask-network
         
    node-site-a:
       build: ./node-site
       volumes:
         - /tmp/shared_logs:/tmp/shared_logs
       ports:
         - 3001:3000
       networks:
         - node-network

    node-site-b:
       build: ./node-site
       volumes:
         - /tmp/shared_logs:/tmp/shared_logs
       ports:
         - 3002:3000
       networks:
         - node-network

networks:
  flask-network: 
    driver: bridge
  node-network: 
    driver: bridge